[www]
user  = www-data
group = www-data

listen = 127.0.0.1:9000

pm                   = dynamic
pm.max_children      = 20
pm.start_servers     = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests      = 500

; Redirect php-fpm stdout/stderr to Docker log stream
catch_workers_output = yes
php_admin_value[error_log]    = /dev/stderr
php_admin_flag[log_errors]    = on

clear_env = no
